// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/partysync.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PartySync_SyncDamage_FullMethodName = "/partysync.PartySync/SyncDamage"
)

// PartySyncClient is the client API for PartySync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PartySyncClient interface {
	// Каждый клиент открывает один bidirectional stream:
	// → шлёт свои DamageUpdate каждые ~2с
	// ← получает PartyState всей комнаты после каждого обновления
	SyncDamage(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DamageUpdate, PartyState], error)
}

type partySyncClient struct {
	cc grpc.ClientConnInterface
}

func NewPartySyncClient(cc grpc.ClientConnInterface) PartySyncClient {
	return &partySyncClient{cc}
}

func (c *partySyncClient) SyncDamage(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DamageUpdate, PartyState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PartySync_ServiceDesc.Streams[0], PartySync_SyncDamage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DamageUpdate, PartyState]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PartySync_SyncDamageClient = grpc.BidiStreamingClient[DamageUpdate, PartyState]

// PartySyncServer is the server API for PartySync service.
// All implementations must embed UnimplementedPartySyncServer
// for forward compatibility.
type PartySyncServer interface {
	// Каждый клиент открывает один bidirectional stream:
	// → шлёт свои DamageUpdate каждые ~2с
	// ← получает PartyState всей комнаты после каждого обновления
	SyncDamage(grpc.BidiStreamingServer[DamageUpdate, PartyState]) error
	mustEmbedUnimplementedPartySyncServer()
}

// UnimplementedPartySyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPartySyncServer struct{}

func (UnimplementedPartySyncServer) SyncDamage(grpc.BidiStreamingServer[DamageUpdate, PartyState]) error {
	return status.Error(codes.Unimplemented, "method SyncDamage not implemented")
}
func (UnimplementedPartySyncServer) mustEmbedUnimplementedPartySyncServer() {}
func (UnimplementedPartySyncServer) testEmbeddedByValue()                   {}

// UnsafePartySyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartySyncServer will
// result in compilation errors.
type UnsafePartySyncServer interface {
	mustEmbedUnimplementedPartySyncServer()
}

func RegisterPartySyncServer(s grpc.ServiceRegistrar, srv PartySyncServer) {
	// If the following call panics, it indicates UnimplementedPartySyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PartySync_ServiceDesc, srv)
}

func _PartySync_SyncDamage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PartySyncServer).SyncDamage(&grpc.GenericServerStream[DamageUpdate, PartyState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PartySync_SyncDamageServer = grpc.BidiStreamingServer[DamageUpdate, PartyState]

// PartySync_ServiceDesc is the grpc.ServiceDesc for PartySync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PartySync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "partysync.PartySync",
	HandlerType: (*PartySyncServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncDamage",
			Handler:       _PartySync_SyncDamage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/partysync.proto",
}
