// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/partysync.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TargetDamage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetDamage) Reset() {
	*x = TargetDamage{}
	mi := &file_proto_partysync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetDamage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetDamage) ProtoMessage() {}

func (x *TargetDamage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partysync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetDamage.ProtoReflect.Descriptor instead.
func (*TargetDamage) Descriptor() ([]byte, []int) {
	return file_proto_partysync_proto_rawDescGZIP(), []int{0}
}

func (x *TargetDamage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TargetDamage) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DamageUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        string                 `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	TotalDamage   int64                  `protobuf:"varint,3,opt,name=total_damage,json=totalDamage,proto3" json:"total_damage,omitempty"`
	Targets       []*TargetDamage        `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
	LastHit       int64                  `protobuf:"varint,5,opt,name=last_hit,json=lastHit,proto3" json:"last_hit,omitempty"`
	LastHitTs     string                 `protobuf:"bytes,6,opt,name=last_hit_ts,json=lastHitTs,proto3" json:"last_hit_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DamageUpdate) Reset() {
	*x = DamageUpdate{}
	mi := &file_proto_partysync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DamageUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DamageUpdate) ProtoMessage() {}

func (x *DamageUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partysync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DamageUpdate.ProtoReflect.Descriptor instead.
func (*DamageUpdate) Descriptor() ([]byte, []int) {
	return file_proto_partysync_proto_rawDescGZIP(), []int{1}
}

func (x *DamageUpdate) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

func (x *DamageUpdate) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *DamageUpdate) GetTotalDamage() int64 {
	if x != nil {
		return x.TotalDamage
	}
	return 0
}

func (x *DamageUpdate) GetTargets() []*TargetDamage {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *DamageUpdate) GetLastHit() int64 {
	if x != nil {
		return x.LastHit
	}
	return 0
}

func (x *DamageUpdate) GetLastHitTs() string {
	if x != nil {
		return x.LastHitTs
	}
	return ""
}

type PlayerSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalDamage   int64                  `protobuf:"varint,1,opt,name=total_damage,json=totalDamage,proto3" json:"total_damage,omitempty"`
	Targets       []*TargetDamage        `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	LastHit       int64                  `protobuf:"varint,3,opt,name=last_hit,json=lastHit,proto3" json:"last_hit,omitempty"`
	LastHitTs     string                 `protobuf:"bytes,4,opt,name=last_hit_ts,json=lastHitTs,proto3" json:"last_hit_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerSnapshot) Reset() {
	*x = PlayerSnapshot{}
	mi := &file_proto_partysync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSnapshot) ProtoMessage() {}

func (x *PlayerSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partysync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSnapshot.ProtoReflect.Descriptor instead.
func (*PlayerSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_partysync_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerSnapshot) GetTotalDamage() int64 {
	if x != nil {
		return x.TotalDamage
	}
	return 0
}

func (x *PlayerSnapshot) GetTargets() []*TargetDamage {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *PlayerSnapshot) GetLastHit() int64 {
	if x != nil {
		return x.LastHit
	}
	return 0
}

func (x *PlayerSnapshot) GetLastHitTs() string {
	if x != nil {
		return x.LastHitTs
	}
	return ""
}

type PartyState struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Players       map[string]*PlayerSnapshot `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // playerName → snapshot
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyState) Reset() {
	*x = PartyState{}
	mi := &file_proto_partysync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyState) ProtoMessage() {}

func (x *PartyState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_partysync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyState.ProtoReflect.Descriptor instead.
func (*PartyState) Descriptor() ([]byte, []int) {
	return file_proto_partysync_proto_rawDescGZIP(), []int{3}
}

func (x *PartyState) GetPlayers() map[string]*PlayerSnapshot {
	if x != nil {
		return x.Players
	}
	return nil
}

var File_proto_partysync_proto protoreflect.FileDescriptor

const file_proto_partysync_proto_rawDesc = "" +
	"\n" +
	"\x15proto/partysync.proto\x12\tpartysync\":\n" +
	"\fTargetDamage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"\xcb\x01\n" +
	"\fDamageUpdate\x12\x16\n" +
	"\x06player\x18\x01 \x01(\tR\x06player\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\x12!\n" +
	"\ftotal_damage\x18\x03 \x01(\x03R\vtotalDamage\x121\n" +
	"\atargets\x18\x04 \x03(\v2\x17.partysync.TargetDamageR\atargets\x12\x19\n" +
	"\blast_hit\x18\x05 \x01(\x03R\alastHit\x12\x1e\n" +
	"\vlast_hit_ts\x18\x06 \x01(\tR\tlastHitTs\"\xa1\x01\n" +
	"\x0ePlayerSnapshot\x12!\n" +
	"\ftotal_damage\x18\x01 \x01(\x03R\vtotalDamage\x121\n" +
	"\atargets\x18\x02 \x03(\v2\x17.partysync.TargetDamageR\atargets\x12\x19\n" +
	"\blast_hit\x18\x03 \x01(\x03R\alastHit\x12\x1e\n" +
	"\vlast_hit_ts\x18\x04 \x01(\tR\tlastHitTs\"\xa1\x01\n" +
	"\n" +
	"PartyState\x12<\n" +
	"\aplayers\x18\x01 \x03(\v2\".partysync.PartyState.PlayersEntryR\aplayers\x1aU\n" +
	"\fPlayersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.partysync.PlayerSnapshotR\x05value:\x028\x012M\n" +
	"\tPartySync\x12@\n" +
	"\n" +
	"SyncDamage\x12\x17.partysync.DamageUpdate\x1a\x15.partysync.PartyState(\x010\x01B7Z5github.com/kirill/gamelogserver/internal/partysync/pbb\x06proto3"

var (
	file_proto_partysync_proto_rawDescOnce sync.Once
	file_proto_partysync_proto_rawDescData []byte
)

func file_proto_partysync_proto_rawDescGZIP() []byte {
	file_proto_partysync_proto_rawDescOnce.Do(func() {
		file_proto_partysync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_partysync_proto_rawDesc), len(file_proto_partysync_proto_rawDesc)))
	})
	return file_proto_partysync_proto_rawDescData
}

var file_proto_partysync_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_partysync_proto_goTypes = []any{
	(*TargetDamage)(nil),   // 0: partysync.TargetDamage
	(*DamageUpdate)(nil),   // 1: partysync.DamageUpdate
	(*PlayerSnapshot)(nil), // 2: partysync.PlayerSnapshot
	(*PartyState)(nil),     // 3: partysync.PartyState
	nil,                    // 4: partysync.PartyState.PlayersEntry
}
var file_proto_partysync_proto_depIdxs = []int32{
	0, // 0: partysync.DamageUpdate.targets:type_name -> partysync.TargetDamage
	0, // 1: partysync.PlayerSnapshot.targets:type_name -> partysync.TargetDamage
	4, // 2: partysync.PartyState.players:type_name -> partysync.PartyState.PlayersEntry
	2, // 3: partysync.PartyState.PlayersEntry.value:type_name -> partysync.PlayerSnapshot
	1, // 4: partysync.PartySync.SyncDamage:input_type -> partysync.DamageUpdate
	3, // 5: partysync.PartySync.SyncDamage:output_type -> partysync.PartyState
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_partysync_proto_init() }
func file_proto_partysync_proto_init() {
	if File_proto_partysync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_partysync_proto_rawDesc), len(file_proto_partysync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_partysync_proto_goTypes,
		DependencyIndexes: file_proto_partysync_proto_depIdxs,
		MessageInfos:      file_proto_partysync_proto_msgTypes,
	}.Build()
	File_proto_partysync_proto = out.File
	file_proto_partysync_proto_goTypes = nil
	file_proto_partysync_proto_depIdxs = nil
}
